# Generated by Django 4.2.1 on 2023-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=10, max_digits=14)),
                ('btw', models.DecimalField(decimal_places=4, max_digits=6)),
                ('image', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
