# Generated by Django 4.2.1 on 2023-05-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_created_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('adres', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=20)),
                ('woonplaats', models.CharField(max_length=100)),
            ],
        ),
    ]
